export enum LayoutModel {
  DRAWER,
  NO_DRAWER,
  MIN_DRAWER,
}

export enum LayoutProp{
  TOP_HEIGHT= 48,
  TABS_HEIGHT= 30,
  LEFT_WIDTH= 250,
  RIGHT_WIDTH= 320,
  MIN_LEFT_WIDTH= 50,
  MIN_LEFT_DRAWER_WIDTH= 200,
}