<template>
    <div
        class="menu-layout"
        @mouseenter="updateShrink(false)"
        @mouseleave="updateShrink(true)"
    >
        <div class="logo">
            <CloudIcon class="h-10 w-10 text-white"/>
        </div>
        <div class="list">
            <div
                :class="['item',menu.path === currentTab?.path?'active-item':'']"
                v-for="menu in menus"
                @click="clickMenu(menu)"
            >
                <ChartBarIcon class="h-5 w-5"/>
                <span class="text-focus-in menu-label" v-if="!isShrink">{{ menu.label }}</span>
            </div>
        </div>
    </div>
</template>

<script setup lang="ts">
import {computed, inject, Ref, ref, unref, watch} from "vue";
import {ChartBarIcon, CloudIcon, ChevronDoubleLeftIcon,ChevronDoubleRightIcon} from '@heroicons/vue/solid'
import tabStore from "../../store/layout/tabStore";
import {Menu} from "../../store/layout/type";

const isShrink = ref(true)
const menuLayoutWidth = inject<Ref<number>>('menuLayoutWidth')
const width = computed(()=>(unref(menuLayoutWidth) + 'px'))
const menus: Menu[] = [
    {label: '主页', icon: '', path: '/home'},
    {label: '系统管理', icon: '', path: '/sys'},
    {label: '工单管理', icon: '', path: '/gd'},
    {label: '工具管理', icon: '', path: '/gj'},
    {label: '日志管理', icon: '', path: '/log'},
]
const currentTab = computed(() => tabStore.currentTab)
const clickMenu = (menu: Menu) => {
    tabStore.commitTab({label: menu.label, path: menu.path})
}

watch(isShrink,()=>{
    if (unref(isShrink)){
        menuLayoutWidth && (menuLayoutWidth.value = 55)
    }else {
        menuLayoutWidth && (menuLayoutWidth.value = 90)
    }
},{immediate:true})
const clickShrink = () => {
    isShrink.value = !unref(isShrink)
}
const updateShrink = (boo:boolean) => {
    isShrink.value = boo
}
</script>

<style scoped lang="less">
.menu-layout {
    transition: 0.3s;
    @apply absolute bg-purple-500 flex flex-col;
    height: 100vh;
    width: v-bind(width);
    z-index: 2;

    .logo {
        @apply flex justify-center p-2;
    }

    .list {
        @apply flex-1 text-gray-200 text-xs p-2 overflow-auto flex flex-col gap-y-2;

        .item {
            @apply flex flex-col gap-y-1 items-center text-center p-3 rounded-lg;
            @apply hover:bg-black hover:bg-opacity-20;
        }

        .active-item {
            @apply bg-black bg-opacity-30;
        }
    }

    .text-focus-in {
        -webkit-animation: text-focus-in 0.2s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
        animation: text-focus-in 0.2s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
    }

    /* ----------------------------------------------
 * Generated by Animista on 2021-11-19 14:9:45
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

    /**
     * ----------------------------------------
     * animation text-focus-in
     * ----------------------------------------
     */
    @-webkit-keyframes text-focus-in {
        0% {
            -webkit-filter: blur(12px);
            filter: blur(12px);
            opacity: 0;
        }
        100% {
            -webkit-filter: blur(0px);
            filter: blur(0px);
            opacity: 1;
        }
    }
    @keyframes text-focus-in {
        0% {
            -webkit-filter: blur(12px);
            filter: blur(12px);
            opacity: 0;
        }
        100% {
            -webkit-filter: blur(0px);
            filter: blur(0px);
            opacity: 1;
        }
    }

    .menu-label{
        display: inline-block;
        white-space: nowrap;
        width: 100%;
        overflow: hidden;
        text-overflow:ellipsis;
    }


}
</style>
